const arkivKjelder = [
  { ar: 1957, fil: '1957_nytt_liv_i_gammal_sport_i_Jostedalen.png', tittel: 'Nytt liv i gamal sport i Jostedalen', avis: 'Lokalavis', samandrag: 'Eldste skriftlege kjelde me kjenner til om skathellekasting. Artikkelen omtalar ein skathellekamp i Jostedalen der Anders Nigard vart kåra som meister. Sporten er omtalt som "gamal" allereie i 1957 — eit tydeleg teikn på at tradisjonen strekker seg langt tilbake i tid.', url: 'https://www.nb.no/items/6971033cb52499f7bb079555b3ffcd94?search=' },
  { ar: 1958, fil: '1958_melkior_fossen_var_skathellemestar.png', tittel: 'Melkior Fossen vart skathellemeister', avis: 'Lokalavis', samandrag: 'Fram Ungdomslag i Jostedalen arrangerte skathelletevling 29. juni 1958 med 36 deltakarar i 12 lag, inkludert lag frå Hafslo. Melkior Fossen vart kåra som vinnar — og dette vart rekna som Jostedalsmeisterskapet. Artikkelen melder at skathellekasting har vorte svært populært i bygda.', url: 'https://www.nb.no/items/263888736d3deb7a24c7b4ce3e3114cd?page=1&search=' },
  { ar: 1958, fil: '1958_arsmote_i_historielaget.png', tittel: 'Årsmøte i Jostedal historielag', avis: 'Lokalavis', samandrag: 'Jostedal historielag held årsmøte og fest i Dølaheimen 17. august 1958. Programmet inkluderte pilkast, skytebane, lykkehjul og skathellekasting — eit teikn på at sporten var ein etablert del av bygdelivet.', url: 'https://www.nb.no/items/e1e769cbd7cc1879097df36c9bbdb916?search=&page=1' },
  { ar: 1961, fil: '1961_marknad_i_doleheimen.png', tittel: 'Marknad i Dølaheimen', avis: 'Lokalavis', samandrag: 'Den årlege marknaden ved Dølaheimen i Jostedalen, med skathellekasting som ein del av programmet.', url: 'https://www.nb.no/items/d1338a88c0373ae75d5b380f8d63502e?page=1&search=' },
  { ar: 1963, fil: '1963_historielag_mote.png', tittel: 'Jostedal historielag møte', avis: 'Lokalavis', samandrag: 'Møte i Jostedal historielag.', url: 'https://www.nb.no/items/1c3ba4c4e88f60eaf978a406daea3731?page=1&search=' },
  { ar: 1964, fil: '1964_Jostedal_historielag.png', tittel: 'Jostedal historielag', avis: 'Lokalavis', samandrag: 'Notis om verksemda i Jostedal historielag.', url: 'https://www.nb.no/items/71582233c2cb844655de184ab5454ccb?page=1&search=' },
  { ar: 1964, fil: '1964_marknad_i_Jostedalen.png', tittel: 'Marknad i Jostedalen', avis: 'Lokalavis', samandrag: 'Den årlege marknaden i Jostedalen med skathellekasting som fast innslag.', url: 'https://www.nb.no/items/13d8b37cbd835d35e4ec189d97cd5539?page=1&search=' },
  { ar: 1965, fil: '1965_marknad_i_dolaheimen.png', tittel: 'Marknad i Dølaheimen', avis: 'Lokalavis', samandrag: 'Marknad ved Dølaheimen med skathellekasting som del av aktivitetane.', url: 'https://www.nb.no/items/48ffa19f192218f44a35a90484ca702b?page=1&search=' },
  { ar: 1972, fil: '1972_langendalsposten.png', tittel: 'Urgamal nasjonalsport i Jostedalen', avis: 'Långendalsposten', samandrag: 'Artikkelen omtalar skathellekasting som ein "urgamal nasjonalsport" i Jostedalen. Dette er den fyrste skriftlege kjelda som tydeleg slår fast at sporten er svært gamal — allereie i 1972 rekna folk sporten som urgamal.', url: 'https://www.nb.no/items/29dd0d369e44678c059226a8763d6618?page=3&search=' },
  { ar: 1978, fil: '1978_skathelle_foleksport.png', tittel: 'Skathellekasting — populær folkesport i Jostedal', avis: 'Sogn og Fjordane', samandrag: 'Sporten beskrivast som ein leik der ein får skathella til å rotere i lufta og falle ned nærmast mogleg målet — ein stein i andre enden av ei om lag 23 meter lang bane. Berre i Jostedalen vert sporten driven, og artikkelen melder at tradisjonen er sterk i dalen.', url: 'https://www.nb.no/items/c771606e4d5834568bf4c319395343e0?page=3&search=' },
  { ar: 1978, fil: '1978_me_ma_satse_pa_skathellemeisterskap.png', tittel: 'Me må satse på skathellemeisterskap', avis: 'Sogn og Fjordane', samandrag: 'Formannen i Jostedal ungdomslag, Norvald Bakken, vil ha eit ordentleg meisterskap. Det er berre i Jostedalen sporten lever, og det treng grendacupar og finalar for å oppretthalde tradisjonen.', url: 'https://www.nb.no/items/f39b99e62dc3c794826de80e7114c459?page=5&search=' },
  { ar: 1978, fil: '1978_Doleheimen.png', tittel: 'Dølaheimen!', avis: 'Sogningen', samandrag: 'Omtale av Dølaheimen som sentrum for marknadsaktivitetar i Jostedalen.', url: 'https://www.nb.no/items/eb4a6e47b108e198e6b1fca499233bf7?page=1&search=' },
  { ar: 1978, fil: '1978_Firda_skathelle.png', tittel: 'Skathellekasting i Firda', avis: 'Firda', samandrag: 'Tidleg omtale av skathellekasting i Firda-avisa.', url: 'https://www.nb.no/items/f5b93fd897f087fe65f4d73c1da5ef09?page=3&search=' },
  { ar: 1978, fil: '1978_Toradar_fest.png', tittel: 'Toradar fest', avis: 'Lokalavis', samandrag: 'Omtale av festarrangement i Jostedalen.', url: 'https://www.nb.no/items/2af83727c991248663a6017be726e7ab?page=1&search=' },
  { ar: 1978, fil: '1978_bygdekunsen_blomar.png', tittel: 'Bygdekunsten blomar', avis: 'Lokalavis', samandrag: 'Om bygdekulturen i Jostedalen, med skathellekasting som døme på levande tradisjon.', url: 'https://www.nb.no/items/48dfd613620f29197a0b6c586a61501f?page=5&search=' },
  { ar: 1979, fil: '1979_For_forste_gong_fylkesmesterskap_i_gaupne.png', tittel: 'For første gong: Fylkesmeisterskap i Gaupne', avis: 'Sogn og Fjordane', samandrag: 'Det fyrste fylkesmeisterskapet i skathellekasting vert halde 24.-26. august 1979 i samband med Husmannsdagane i Gaupne. Jostedal ungdomslag arrangerer saman med avisa Sogn og Fjordane. Banelengde 20-23 meter, tre deltakarar per lag. Stortingsmann Kåre Øvregard er kommentator.', url: 'https://www.nb.no/items/af3f6a7b2ccf15d72759a4a25bf78104?page=7&search=' },
  { ar: 1979, fil: '1979_rutinerte_jostedoler.png', tittel: 'Rutinerte jostedøler vart skathellemeisterar', avis: 'Sogn og Fjordane', samandrag: 'Rapportering frå fylkesmeisterskapet i Gaupne. Erfarne jostedøler stakk av med sigeren — vinnarlag: Erik Fossen, Torleiv Vigdal og Per Bakken.', url: 'https://www.nb.no/items/f9ed4c30ecdad16718926ca71ad86190?page=5&search=' },
  { ar: 1979, fil: '1979_fylkesmesterskap_i_skathellekasting.png', tittel: 'Fylkesmeisterskap i Luster', avis: 'Sogn og Fjordane', samandrag: 'Artikkelen omtalar sporten som "nasjonalsport" i Jostedalen i lang tid. Det vert peika på at folk frå Stryn ofte deltok, sidan det var trafikk over breen mellom Jostedal og Stryn i gamle dagar.', url: 'https://www.nb.no/items/12e4d585550f669089bb04560c92347b?page=3&search=' },
  { ar: 1979, fil: '1979_Bergens_arbeiderblad.png', tittel: 'Skathellekasting i Luster', avis: 'Bergens Arbeiderblad', samandrag: 'Bergensavisa omtalar fylkesmeisterskapet i skathellekasting i samband med Husmannsdagane i Luster.', url: 'https://www.nb.no/items/12e4d585550f669089bb04560c92347b?page=3&search=' },
  { ar: 1979, fil: '1979_Husmannsdagar_borkabrod_og_skathellekasting.png', tittel: 'Husmannsdagar med borkebrød og skathellekasting', avis: 'Sogn og Fjordane', samandrag: 'Stor reportasje frå Husmannsdagane i Luster. 7000 menneske var innom arrangementet. Jostedølene dominerte skathellekastinga — vinnarlag: Erik Fossen, Torleiv Vigdal og Per Bakken.', url: 'https://www.nb.no/items/7c503a235f6192dc4b5eb93fe5a94ada?page=0&search=' },
  { ar: 1979, fil: '1979_Husmannsdagar_borkabrod_og_skathellekasting_2.png', tittel: 'Husmannsdagar — del 2', avis: 'Sogn og Fjordane', samandrag: 'Vidare reportasje frå Husmannsdagane i Luster 1979.', url: 'https://www.nb.no/items/7c503a235f6192dc4b5eb93fe5a94ada?page=0&search=' },
  { ar: 1979, fil: '1979_Firda_folkeblad.png', tittel: 'Skathellekasting i Firda Folkeblad', avis: 'Firda Folkeblad', samandrag: 'Florø-avisa Firda Folkeblad dekker skathellekasting i Jostedalen.', url: 'https://www.nb.no/items/9099fb9cdc8acfe05c9f5aee6c8e0ebc?page=1&search=' },
  { ar: 1979, fil: '1979_Firda_reglar_for_skathelle.png', tittel: 'Reglane for skathellekasting', avis: 'Firda', samandrag: 'Reglane for skathellekasting publisert i Firda-avisa: 20-23 meter bane, tre kastarar per lag, fem poeng vinn settet, utslagsturnering til finalen.', url: 'https://www.nb.no/items/1f28c09a9cd78fc8b3c23b1a4a4260db?page=1&search=' },
  { ar: 1979, fil: '1979_Skathellekasting_i_Gaupne.png', tittel: 'Skathellekasting i Gaupne', avis: 'Sogn og Fjordane', samandrag: 'Omtale av skathellekonkurransen i Gaupne under Husmannsdagane 1979.', url: 'https://www.nb.no/items/11d6b3b1e4282176f1d344a670d544e5?page=5&search=' },
  { ar: 1979, fil: '1979_Fylkesmesterskap_i_skathellekasting_meira.png', tittel: 'Fylkesmeisterskap — meir info', avis: 'Sogn og Fjordane', samandrag: 'Tilleggsinformasjon om fylkesmeisterskapet. Semifinalar og finalar på sundag med Kåre Øvregard som kommentator.', url: 'https://www.nb.no/items/6820f9a578598e041eb889439e293abc?page=5&search=' },
  { ar: 1979, fil: '1979_fylkesmesterskap_i_skathellekasting_i_luster.png', tittel: 'Fylkesmeisterskap i skathellekasting i Luster', avis: 'Lokalavis', samandrag: 'Omtale av fylkesmeisterskapet i Luster 1979.', url: 'https://www.nb.no/items/af3f6a7b2ccf15d72759a4a25bf78104?page=7&search=' },
  { ar: 1979, fil: '1979_Litt_av_kvart_pa_husmansdagane.png', tittel: 'Litt av kvart på Husmannsdagane', avis: 'Sogn og Fjordane', samandrag: 'Oversikt over aktivitetar på Husmannsdagane, med skathellekasting som eit av høgdepunkta.', url: 'https://www.nb.no/items/a4f54b73718f8f240d7eb2c0daaf71f8?page=1&search=' },
  { ar: 1979, fil: '1979_vil_dette_glorifisere_husmannstida.png', tittel: 'Vil dette glorifisere husmannstida?', avis: 'Sogn og Fjordane', samandrag: 'Debattartikkel om Husmannsdagane som arrangement. Skathellekasting omtalt positivt som ekte folkesport utan kommersialisering.', url: 'https://www.nb.no/items/288d661d1fafed41045c8f92a8f3d293?page=1&search=' },
  { ar: 1980, fil: '1980_Marknad_i_Framheim.png', tittel: 'Marknad i Framheim', avis: 'Lokalavis', samandrag: 'Marknad i Framheim med skathellekasting på programmet.', url: 'https://www.nb.no/items/f3a1d6129ec016c368a36f40d4a3a9d7?page=3&search=' },
  { ar: 1980, fil: '1980_nyformann_i_Fram_ungdommslag.png', tittel: 'Ny formann i Fram ungdomslag', avis: 'Lokalavis', samandrag: 'Skifte i leiinga i ungdomslaget Fram, som er ein av hovudarrangørane av skathellekastinga.', url: 'https://www.nb.no/items/f3a1d6129ec016c368a36f40d4a3a9d7?page=3&search=' },
  { ar: 1981, fil: '1981_marknadsplan.png', tittel: 'Marknadsplan 1981', avis: 'Lokalavis', samandrag: 'Plan for marknadshelgi i Jostedalen 1981 med skathellekasting på programmet.', url: 'https://www.nb.no/items/84a802a12f83e819b4ba9cf8971791ee?page=3&search=' },
  { ar: 1982, fil: '1982_marknadshelg_i_framheim.png', tittel: 'Marknadshelg i Framheim', avis: 'Lokalavis', samandrag: 'Marknadshelg ved Framheim 1982 med skathellekasting.', url: 'https://www.nb.no/items/62e0972714e3f8ba2e483944953ad9fa?page=5&search=' },
  { ar: 1982, fil: '1982_marknad_i_dolaheimen.png', tittel: 'Marknad i Dølaheimen', avis: 'Lokalavis', samandrag: 'Marknad ved Dølaheimen 1982.', url: 'https://www.nb.no/items/578e8804defb9cd1148847559b5c21d3?page=3&search=' },
  { ar: 1982, fil: '1982_marknad_i_dolaheimen_oppsett.png', tittel: 'Marknad i Dølaheimen — programoppsett', avis: 'Lokalavis', samandrag: 'Programoppsett for marknadshelgi ved Dølaheimen 1982.', url: 'https://www.nb.no/items/5fb1dd1d3951a64718c0995ac7707708?page=5' },
  { ar: 1983, fil: '1983_Sommarfest_i_framheim.png', tittel: 'Sommarfest i Framheim', avis: 'Lokalavis', samandrag: 'Sommarfest med skathellekasting i Framheim 1983.', url: 'https://www.nb.no/items/b7241f46c865026f7b6fea1f7aa3ffe9?page=5&search=' },
  { ar: 1983, fil: '1983_Marknad_i_doleheimen.png', tittel: 'Marknad i Dølaheimen', avis: 'Lokalavis', samandrag: 'Tradisjonell marknad ved Dølaheimen 1983.', url: 'https://www.nb.no/items/6d6cb15a778caa057c545159b754adf1?page=11&search=' },
  { ar: 1983, fil: '1983_Marknadshelg_i_dolaheimen.png', tittel: 'Marknadshelg i Dølaheimen', avis: 'Lokalavis', samandrag: 'Omtale av marknadshelgi 1983.', url: 'https://www.nb.no/items/71f0095856dfe934f6aca714289e57c9?page=3&search=' },
  { ar: 1983, fil: '1983_sogn_og_fjordane_Marknadshelg_i_dolaheimen.png', tittel: 'Marknadshelg i Dølaheimen', avis: 'Sogn og Fjordane', samandrag: 'Sogn og Fjordane dekker marknadshelgi ved Dølaheimen 1983.', url: 'https://www.nb.no/items/8e7aad479ffe9a0afeb1278d49b82175?page=5&search=' },
  { ar: 1983, fil: '1983_marknadshelg_i_jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Omtale av marknadshelgi i Jostedalen 1983.', url: 'https://www.nb.no/items/b95b918d093058ed0f68a6d03354e3b2?page=1&search=' },
  { ar: 1983, fil: '1983_aksjon_i_sogndal.png', tittel: 'Aksjon i Sogndal', avis: 'Sogn og Fjordane', samandrag: 'Skathellekasting-aktivitet i Sogndal 1983.', url: 'https://www.nb.no/items/4a077b24095c221625ef6f721972e0bf?page=7&search=' },
  { ar: 1984, fil: '1984_skathellekasting_i_doleheimen.png', tittel: 'Skathellekasting i Dølaheimen', avis: 'Sogn og Fjordane', samandrag: 'Skathellekasting står i sentrum for marknadshelgi ved Dølaheimen 1984.', url: 'https://www.nb.no/items/29483510ab2a594fbac6031f7a26f750?page=5&search=' },
  { ar: 1984, fil: '1984_marknadshelgi.png', tittel: 'Marknadshelgi 1984', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen omteler marknadshelgi 1984.', url: 'https://www.nb.no/items/79b8e07d89d14bdeb54b62baa77bdbb0?page=1&search=' },
  { ar: 1984, fil: '1984_stormarknadshelg_i_doleheimen.png', tittel: 'Stormarknadshelg i Dølaheimen', avis: 'Lokalavis', samandrag: 'Den store marknadshelgi ved Dølaheimen 1984 med skathellekasting som hovudattraksjon.', url: 'https://www.nb.no/items/79b8e07d89d14bdeb54b62baa77bdbb0?page=1&search=' },
  { ar: 1985, fil: '1985_Dolaheimen_skathellekastinga_sitt_mekka.png', tittel: 'Dølaheimen — skathellekastinga sitt mekka', avis: 'Sogn og Fjordane', samandrag: '"Fotballen har sitt mekka på Wembley. Skathellekastinga har sitt ved Dølaheimen." Artikkelen dokumenterer korleis sporten lever vidare i Jostedalen — det einaste staden i landet der ein driv med skathellekasting. Ein dokumentasjon på kva Dølaheimen tyder for sporten.', url: 'https://www.nb.no/items/2daf44de52ecd85fcbc60728abf880e6?page=9&search=' },
  { ar: 1985, fil: '1985_Marknadshelgi.png', tittel: 'Marknadshelgi 1985', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen omtaler marknadshelgi 11. juli 1985.', url: 'https://www.nb.no/items/82b2c125e17141cbca22a7a21b4064bf?page=1&search=' },
  { ar: 1985, fil: '1985_Marknadshelg_i_dolaheimen.png', tittel: 'Marknadshelg i Dølaheimen', avis: 'Lokalavis', samandrag: 'Marknadshelg ved Dølaheimen 1985.', url: 'https://www.nb.no/items/ff6fe4110e8d2530805746857c2d1f09?page=1&search=' },
  { ar: 1985, fil: '1985_Marknadshegi_i_dolaheimen_plan.png', tittel: 'Marknadshelgi — plan', avis: 'Lokalavis', samandrag: 'Planoppsett for marknadshelgi ved Dølaheimen 1985.', url: 'https://www.nb.no/items/ff6fe4110e8d2530805746857c2d1f09?page=1&search=' },
  { ar: 1985, fil: '1985_Programmet_for_marknadshelgi.png', tittel: 'Programmet for marknadshelgi', avis: 'Lokalavis', samandrag: 'Detaljert program for marknadshelgi 1985 med skathellekasting på hovudprogrammet.', url: 'https://www.nb.no/items/82b2c125e17141cbca22a7a21b4064bf?page=1&search=' },
  { ar: 1985, fil: '1985_marknadshelg_i_framheim.png', tittel: 'Marknadshelg i Framheim', avis: 'Lokalavis', samandrag: 'Marknadshelg i Framheim 1985 med skathellekasting.', url: 'https://www.nb.no/items/def2f04397a3e5310ea7e740d6365ab2?page=5&search=' },
  { ar: 1985, fil: '1985_marknad_i_jostedalen.png', tittel: 'Marknad i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknad i Jostedalen 1985.', url: 'https://www.nb.no/items/82b2c125e17141cbca22a7a21b4064bf?page=1&search=' },
  { ar: 1985, fil: '1985_stormarknads_helg_i_dolaheimen.png', tittel: 'Stormarknadshelg i Dølaheimen', avis: 'Lokalavis', samandrag: 'Stor marknadshelg ved Dølaheimen 1985.', url: 'https://www.nb.no/items/7962224cb6fe2b1ebac647bdb73d39ea?page=5&search=' },
  { ar: 1986, fil: '1986_marknadshelg_i_dolaheimen.png', tittel: 'Marknadshelg i Dølaheimen', avis: 'Lokalavis', samandrag: 'Marknadshelg ved Dølaheimen august 1986.', url: 'https://www.nb.no/items/4af2ea3f4936bbb82969fe45548d23a3?page=3&search=' },
  { ar: 1986, fil: '1986_makrnadshelg_august_i_dolaheimen.png', tittel: 'Marknadshelg i august', avis: 'Lokalavis', samandrag: 'August-marknad ved Dølaheimen 1986.', url: 'https://www.nb.no/items/098d84c419d9652ba4410ea501ba4ead?page=1&search=' },
  { ar: 1986, fil: '1986_Marknad_i_doleheimen_oppsett.png', tittel: 'Marknad i Dølaheimen — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for marknaden ved Dølaheimen 1986.', url: 'https://www.nb.no/items/7faa5499ca5d274cdc505199504a1db4?page=11&search=' },
  { ar: 1986, fil: '1986_arsmelding_fra_Jostedal_ungdommslag.png', tittel: 'Årsmelding frå Jostedal ungdomslag', avis: 'Lokalavis', samandrag: 'Årsmelding frå ungdomslaget som er hovudarrangør av skathellekastinga i Jostedalen.', url: 'https://www.nb.no/items/b395873d055142cf026ce75012d27b28?page=13&searchTexq=' },
  { ar: 1986, fil: '1986_marknadshelg_i_jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1986.', url: 'https://www.nb.no/items/4af2ea3f4936bbb82969fe45548d23a3?page=3&search=' },
  { ar: 1987, fil: '1987_skathellekasting_er_topp.png', tittel: 'Skathellekasting er topp', avis: 'Sogn og Fjordane', samandrag: 'Stor reportasje med fleire bilete. "Sei skathellekasting, og jostedølene vert andektige i blikket." Sporten omtalt som nasjonalsport i Jostedalen og ein sport som går på tvers av generasjonsskilje. Folk i alle aldrar sit på sidelina. "Skathellekasting må vera ein ypperleg form for sosial omgang."', url: 'https://www.nb.no/items/c39c97ed2ee7668e2f635aa9ce260e6c?page=1&search=' },
  { ar: 1987, fil: '1987_Marknad_i_Jostedalen_med_ein_vri.png', tittel: 'Marknad i Jostedalen med ein vri', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen omteler den årlege marknaden i Jostedalen 1987.', url: 'https://www.nb.no/items/9cdae8a429ba5a93bb9254356bdcc09e?page=5&search=' },
  { ar: 1987, fil: '1987_stormarknad_i_Jostedalen.png', tittel: 'Stor marknadshelg i Jostedalen', avis: 'Sogningen-Sogns Avis', samandrag: 'Stor marknadshelg i Jostedalen 1987 med skathellekasting som hovudattraksjon.', url: 'https://www.nb.no/items/db2668b95450452d534aef09e8c7025d?search=' },
  { ar: 1987, fil: '1987_marknadshelg_i_Jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Omtale av marknadshelgi 21. juli 1987.', url: 'https://www.nb.no/items/64969966385d3026a4885da74e1e2269?page=15&search=' },
  { ar: 1987, fil: '1987_Stor_marknad_i_jostedalen_berre_skrift.png', tittel: 'Stor marknad — tekstomtale', avis: 'Lokalavis', samandrag: 'Tekstomtale av marknaden i Jostedalen 1987.', url: 'https://www.nb.no/items/5566ee7530a57bd8c8221f2f72872214?page=1&search=' },
  { ar: 1987, fil: '1987_velkommen_til_Jostedal.png', tittel: 'Velkommen til Jostedal', avis: 'Lokalavis', samandrag: 'Velkomstomtale for marknadshelgi i Jostedalen 1987.', url: 'https://www.nb.no/items/75bc77b585ec1a0d85041820ee93431f?page=1&search=' },
  { ar: 1987, fil: '1987_Velkomne_i_jostedal.png', tittel: 'Velkomne i Jostedal', avis: 'Lokalavis', samandrag: 'Velkomstomtale for marknadsarrangementet 1987.', url: 'https://www.nb.no/items/ee2c3718d3a5f9935e571d9bf9ba4a7d?page=1&search=' },
  { ar: 1987, fil: '1987_storinnsats_med_langhuset.png', tittel: 'Storinnsats med langhuset', avis: 'Lokalavis', samandrag: 'Omtale av byggjeprosjekt i Jostedalen 1987.', url: 'https://www.nb.no/items/23355a8dcd3755403fdfea28cfcc97e2?page=7&search=' },
  { ar: 1988, fil: '1988_populaert_med_skathellekasting.png', tittel: 'Populært med skathellekasting i Jostedalen', avis: 'Sogningen-Sogns Avis', samandrag: 'Reportasje frå Brehelgi 88. Jarle Ruud viser kasteteknikken. "Skathellekasting er ein gamal tradisjon i Jostedalen, og for å verta ein god kastar må ein øve og atter øve." Skathella er ein vanleg gråstein som kastarane finn i elveleiet, og som blir kasta med ein spesiell teknikk.', url: 'https://www.nb.no/items/408e4b7256ff0d66dbf47afc8583b7a1?page=3&search=' },
  { ar: 1988, fil: '1988_ny_marknadshelg_i_Jostedalen.png', tittel: 'Ny marknadshelg i Jostedalen', avis: 'Sogningen-Sogns Avis', samandrag: 'Omtale av ny marknadshelg i Jostedalen 1988.', url: 'https://www.nb.no/items/6ea21e1096f732381f543714d08f940b?page=1&search=' },
  { ar: 1988, fil: '1988_konsert_med_Rune_Rudberg.png', tittel: 'Konsert med Rune Rudberg', avis: 'Lokalavis', samandrag: 'Rune Rudberg kjem til Jostedalen som del av marknadshelgi 1988 — eit av dei store åra for Jostedalsmarknaden.', url: 'https://www.nb.no/items/d3ffd9190571cfd50be860c0f24d1724?page=1&search=' },
  { ar: 1988, fil: '1988_Marknadshelgi_88_den_gongen_rune_rudberg_kom_til_dalen.png', tittel: 'Marknadshelgi 88 — den gongen Rune Rudberg kom til dalen', avis: 'Lokalavis', samandrag: 'Tilbakeblikk på det store marknadsåret 1988 då Rune Rudberg kom til Jostedalen.', url: 'https://www.nb.no/items/a5a773ca765e2ce8692d4938bc6c77b6?page=11&search=' },
  { ar: 1988, fil: '1988_Marknadenn_gav_meir_smak.png', tittel: 'Marknaden gav meir smak', avis: 'Lokalavis', samandrag: 'Etterspel etter ein vellukka marknadshelg i Jostedalen 1988.', url: 'https://www.nb.no/items/0cad4e2e4924fc7d289cbf5e6634e27f?page=17&search=' },
  { ar: 1988, fil: '1988_brehelgi_i_Jostedalen.png', tittel: 'Brehelgi i Jostedalen', avis: 'Lokalavis', samandrag: 'Brehelg-arrangementet i Jostedalen 1988 med skathellekasting på programmet.', url: 'https://www.nb.no/items/3cb9850f8d1eecadcaaab9d0f0acdd76?page=19&search=' },
  { ar: 1988, fil: '1988_Brehelgi_i_Jostedalenoppsett.png', tittel: 'Brehelgi — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for Brehelgi i Jostedalen 1988.', url: 'https://www.nb.no/items/ca3178ca1c03d6555df2ae947f1d21b9?page=15&search=' },
  { ar: 1989, fil: '1989_brehelg_og_spennande_opplegg.png', tittel: 'Brehelg og spennande opplegg', avis: 'Lokalavis', samandrag: 'Spennande program for brehelga i Jostedalen 1989 med skathellekasting.', url: 'https://www.nb.no/items/805bd5e63b74b561d8ea3e0d740e066c?page=3&search=' },
  { ar: 1989, fil: '1989_Brehelg_i_Jostedal.png', tittel: 'Brehelg i Jostedal', avis: 'Lokalavis', samandrag: 'Brehelg-arrangementet i Jostedal 1989.', url: 'https://www.nb.no/items/0cdf2746bcdb132d6a3dc199ddcec819?page=3&search=' },
  { ar: 1989, fil: '1989_brehelg_i_Jostedalen.png', tittel: 'Brehelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Brehelg i Jostedalen 1989 med skathellekasting.', url: 'https://www.nb.no/items/eaffedf738728c0a8bea78444d0dca1b?page=19&search=' },
  { ar: 1989, fil: '1989_marknadshelg_i_Jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1989 med skathellekasting på programmet.', url: 'https://www.nb.no/items/840e55c94a3c0acd0060e8a8d2e74869?page=13&search=' },
  { ar: 1989, fil: '1989_marknadshelg_i_Jostedalen_Sogningen.png', tittel: 'Marknadshelg — Sogningen', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen omteler marknadshelgi i Jostedalen 1989.', url: 'https://www.nb.no/items/4a65fb539d5eaa03f721444f278c113d?page=23&search=' },
  { ar: 1990, fil: '1990_skathellekasting.png', tittel: 'Skathellekasting', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen omteler skathellekasting i Jostedalen 1990.', url: 'https://www.nb.no/items/d437e2ddd775719bf6cc029e7a04f8d4?search=&page=13' },
  { ar: 1990, fil: '1990_Skathellekasting_og_dans.png', tittel: 'Skathellekasting og dans', avis: 'Lokalavis', samandrag: 'Skathellekasting og dans på marknadshelgi i Jostedalen 1990.', url: 'https://www.nb.no/items/68190bdbf517671499959935bac0a750?page=19&search=' },
  { ar: 1990, fil: '1990_Jostedalen_marknadshelg.png', tittel: 'Jostedalen marknadshelg', avis: 'Lokalavis', samandrag: 'Jostedalen marknadshelg 1990 med skathellekasting.', url: 'https://www.nb.no/items/9cd185ac36e2a05ebf95c3a0bd74afb5?page=11&search=' },
  { ar: 1990, fil: '1990_Jostdal_ungdommslag_marknad.png', tittel: 'Jostedal ungdomslag — marknad', avis: 'Lokalavis', samandrag: 'Ungdomslaget sin marknad i Jostedalen 1990.', url: 'https://www.nb.no/items/8e6c9195dde8e299bd6ce20e1b05ac00?page=21&search=' },
  { ar: 1990, fil: '1990_oversikt_over_marknadshelgi.png', tittel: 'Oversikt over marknadshelgi', avis: 'Lokalavis', samandrag: 'Full oversikt over programmet for marknadshelgi i Jostedalen 1990.', url: 'https://www.nb.no/items/d6f6911ad06d446d7f3f969bddbc475d?page=25&search=' },
  { ar: 1990, fil: '1990_marknadshelgi_oppsett.png', tittel: 'Marknadshelgi — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for marknadshelgi i Jostedalen 1990.', url: 'https://www.nb.no/items/d6f6911ad06d446d7f3f969bddbc475d?page=25&search=' },
  { ar: 1990, fil: '1990_sogningen_oppsett_for_marknadshelgi.png', tittel: 'Sogningen — oppsett for marknadshelgi', avis: 'Sogningen-Sogns Avis', samandrag: 'Sogningen sitt oppsett for marknadshelgi 1990.', url: 'https://www.nb.no/items/3af0e3e0b82a072daf8d5c6f95511084?page=13&search=' },
  { ar: 1991, fil: '1991_kulturdagane_i_skjolden.png', tittel: 'Kulturdagane i Skjolden', avis: 'Lokalavis', samandrag: 'Skathellekasting på kulturdagane i Skjolden 1991 — sporten spreidd ut over kommunen.', url: 'https://www.nb.no/items/a3b38b9f1290fe02d8f43bc2b8637b51?page=15&search=' },
  { ar: 1991, fil: '1991_kulturdagar_i_skjolden.png', tittel: 'Kulturdagar i Skjolden', avis: 'Lokalavis', samandrag: 'Kulturdagar i Skjolden 1991 med skathellekasting på programmet.', url: 'https://www.nb.no/items/1458dbed69f57c01626c0e6826541beb?page=25&search=' },
  { ar: 1991, fil: '1991_marknadshelg.png', tittel: 'Marknadshelg 1991', avis: 'Sogn og Fjordane', samandrag: 'Marknadshelg i Jostedalen 1991 med skathellekasting.', url: 'https://www.nb.no/items/ef8a2b5a9e2845ff20a9420f69376e3f?page=5&search=' },
  { ar: 1992, fil: '1992_skathellekasting_i_doleheimen.png', tittel: 'Skathellekasting i Dølaheimen', avis: 'Sogningen-Sogns Avis', samandrag: 'Stor omtale av skathellekasting ved Dølaheimen 1992. Sporten lever vidare som fast innslag på marknadshelgi.', url: 'https://www.nb.no/items/36835ed2bb94363b0ec0a798a5af022f?page=9&search=' },
  { ar: 1992, fil: '1992_Marknadshelg_i_Jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1992.', url: 'https://www.nb.no/items/c35baa35021a351e7db503f4b3a0a97f?page=15&search=' },
  { ar: 1992, fil: '1992_minimarknad_i_Jostedal.png', tittel: 'Minimarknad i Jostedal', avis: 'Lokalavis', samandrag: 'Mindre marknadsarrangement i Jostedal 1992.', url: 'https://www.nb.no/items/204b62495837c31f4e242507e967ac8a?page=21&search=' },
  { ar: 1992, fil: '1992_mini-marknad.png', tittel: 'Mini-marknad', avis: 'Lokalavis', samandrag: 'Mini-marknad i Jostedalen 1992.', url: 'https://www.nb.no/items/cf18e4565386adb2d5e204f08a75c839?page=1&search=' },
  { ar: 1993, fil: '1993_marknadshelgi_i_Jostedalen.png', tittel: 'Marknadshelgi i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1993 med skathellekasting.', url: 'https://www.nb.no/items/91b1c469e5a4316655aed65334950ae0?page=19&search=' },
  { ar: 1994, fil: '1994_aleine_om_skathellekasting.png', tittel: 'Åleine om skathellekasting', avis: 'Sogn Avis', samandrag: 'Stor reportasje med tittelen "Åleine om skathellekasting". Jostedølene er den einaste bygda i landet med eigen sport. Edvin Flati og Magnus Nigard (81 år) uttaler seg. Magnus fortel: "Hella må vera flat under, og ikkje for tjukk." Sporten samlar folk i alle aldrar, men det er karane som kastar mest.', url: 'https://www.nb.no/items/59fe4978afddb51498db0a6303dcfa0f?page=7&search=' },
  { ar: 1994, fil: '1994_marknad_oppsett.png', tittel: 'Marknad — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for marknadshelgi i Jostedalen 1994.', url: 'https://www.nb.no/items/6915edc9bf32b0e59ea9baa5cb260717?page=27&search=' },
  { ar: 1994, fil: '1994_miljoveke_i_Jostedalen.png', tittel: 'Miljøveke i Jostedalen', avis: 'Lokalavis', samandrag: 'Miljøveke i Jostedalen 1994 med skathellekasting på programmet.', url: 'https://www.nb.no/items/1efdbb382b00ebcf547cefc2db8217bb?page=1&search=' },
  { ar: 1995, fil: '1995_marknadshelg.png', tittel: 'Marknadshelg 1995', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1995 med skathellekasting.', url: 'https://www.nb.no/items/018814e11b921ed38df2336b30ee7121?page=1&search=' },
  { ar: 1996, fil: '1996_skathell_som_barneleik.png', tittel: 'Skathelle som barneleik', avis: 'Lokalavis', samandrag: '"Skathellekasting dreiv me med når me var vorten litt eldre, rundt konfirmasjonsalderen." Eldre jostedøler fortel om barndomsleikar. Skathellekasting var noko ein begynte med som tenåring — ein sport som gjekk i arv frå generasjon til generasjon.', url: 'https://www.nb.no/items/0f265733843066549fb16733d8568066?page=13&search=' },
  { ar: 1996, fil: '1996_marknadshelgi.png', tittel: 'Marknadshelgi 1996', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1996.', url: 'https://www.nb.no/items/7edf474bb29ab14f510a30db152d80ee?page=19&search=' },
  { ar: 1997, fil: '1997_lange_baskar_i_varm_sol.png', tittel: 'Lange baskar i varm sol', avis: 'Sogn Avis', samandrag: 'Stor reportasje frå marknadshelgi 1997. "Publikum på skathellekasting er ikkje av det bråkete slaget, men lyttar til mumling frå seniorbenken." Sporten omtalt som "den gamle tradisjonen" — utan kostbart utstyr, open for alle, og med sterk tilknyting til Jostedalen og familien.', url: 'https://www.nb.no/items/ed8647f426acec327eecd7ee703aa67d?page=9&search=' },
  { ar: 1997, fil: '1997_Hordaland.png', tittel: 'Hordaland omtalar skathellekasting', avis: 'Hordaland', samandrag: 'Hordaland-avisa omteler skathellekasting i Jostedalen — sporten er no kjend langt utanfor eige fylke.', url: 'https://www.nb.no/items/4c3a2fa28c006d45fd1a902c6b61b504?page=0&search=' },
  { ar: 1998, fil: '1998_marknadshelgi.png', tittel: 'Marknadshelgi 1998', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 1998 med skathellekasting.', url: 'https://www.nb.no/items/3f2a61fc2feda4bed87a84891e54f473?page=19&search=' },
  { ar: 1999, fil: '1999_om_skathellekasting.png', tittel: 'Om skathellekasting — lang tradisjon', avis: 'Lokalavis', samandrag: '"Skathellekastinga har lang tradisjon i Jostedalen, og det er viktig at me tek vare på denne artige aktiviteten." Artikkelen dokumenterer at skathellekasting i Jostedalen truleg startar frå byrjinga av 1900-talet. Det var oftast karane som kasta, men jenter deltok òg i den årlege konkurransen.', url: 'https://www.nb.no/items/a300c3b7f1871bf702db844c9cc85aa7?page=7&search=' },
  { ar: 1999, fil: '1999_bjorn_og_skathelle_pa_marknaden.png', tittel: 'Bjørn og skathelle på marknaden', avis: 'Lokalavis', samandrag: 'Marknadshelg 1999 med skathellekasting og andre attraksjonar ved Dølaheimen.', url: 'https://www.nb.no/items/1f7171b1ee9060ece172e00c8541074a?page=11&search=' },
  { ar: 1999, fil: '1999_skathellebilde.png', tittel: 'Skathellekasting under marknadshelgi', avis: 'Lokalavis', samandrag: '"Skathellekasting er spesielt for Jostedalen og mange deltok i den spennande konkurransen under marknadshelga." Bilete av kastar i aksjon.', url: 'https://www.nb.no/items/a300c3b7f1871bf702db844c9cc85aa7?page=7&search=' },
  { ar: 1999, fil: '1999_museumet_pa_kaupanger.png', tittel: 'Museum på Kaupanger', avis: 'Lokalavis', samandrag: 'Skathellekasting dokumentert i museumssamanheng på Kaupanger 1999.', url: 'https://www.nb.no/items/1ff6ac9be4da781b4e96385d0c1e729d?page=11&search=' },
  { ar: 2000, fil: '2000_spennande_og_variert_skule_og_bygde_avis.png', tittel: 'Spennande og variert skule- og bygdeavis', avis: 'JSA — Jostedal skule- og bygdeavis', samandrag: 'Omtale av Jostedal skule- og bygdeavis (JSA) med skathellekasting som ein del av det lokale kulturlivet.', url: 'https://www.nb.no/items/0ea1086c9dd1e55ac01f0a2a534853aa?page=5&search=' },
  { ar: 2002, fil: '2002_presisjon_og_prestisje.png', tittel: 'Presisjon og prestisje', avis: 'Sogn Avis', samandrag: '"Du kan høyre ein knappenål dette i det skathella flyg gjennom lufta." Stor reportasje om skathellekasting som presisjonssport. Tom Røysi (34) er avbilda i kasteposen. Sporten omtalt som årets mest prestisjetunge konkurranse i Jostedalen. Familiebandet til sporten er sterkt — deltakarane stiller alltid opp.', url: 'https://www.nb.no/items/7d1032f70b7210cccca98ad88ce12457?page=9&search=' },
  { ar: 2002, fil: '2002_marknadshelg.png', tittel: 'Marknadshelg 2002', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2002.', url: 'https://www.nb.no/items/25d47142d9f608f38cc37f7bbe0e125d?page=17&search=' },
  { ar: 2003, fil: '2003_marknadshelgi.png', tittel: 'Marknadshelgi 2003', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2003 med skathellekasting.', url: 'https://www.nb.no/items/51e929746e439cbdbbfe1865ed1a0bf4?page=19&search=' },
  { ar: 2004, fil: '2004_Havard_sviktar_ikkje_med_skathella.png', tittel: 'Håvard sviktar ikkje med skathella', avis: 'Sogn Avis', samandrag: 'Stor reportasje med dramatisk bilete av Håvard Hesjevoll i hopp-kast. Jostedølene fryktar for framtida til skathellekastinga — dei unge er ikkje like aktive som dei eldre. "Rekrutteringa er for dårleg," seier Anders Grov. Marknadshelga dette året hadde om lag 40.000 kroner netto i inntekter.', url: 'https://www.nb.no/items/43fe11d33298bae5e9e3da96e51fa4e3?page=9&search=' },
  { ar: 2004, fil: '2004_marknadshelg_i_Jostedalen.png', tittel: 'Marknadshelg i Jostedalen', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2004.', url: 'https://www.nb.no/items/127b0876588c53440dee43445d252c1f?page=15&search=' },
  { ar: 2004, fil: '2004_full_gass_pa_bjelde.png', tittel: 'Full gass på Bjelde', avis: 'Lokalavis', samandrag: 'Stor aktivitet og engasjement kring marknadshelgi 2004.', url: 'https://www.nb.no/items/1ff722b6a01345ede34f1eb6edce4faa?page=9&search=' },
  { ar: 2004, fil: '2004_sogndal_putballbane.png', tittel: 'Sogndal putballbane', avis: 'Lokalavis', samandrag: 'Notis frå Sogndal-området 2004.', url: 'https://www.nb.no/items/8549db13d7df333555e763ad4ad890be?page=29&search=' },
  { ar: 2005, fil: '2005_Summarmarknad.png', tittel: 'Sommarmarknad 2005', avis: 'Lokalavis', samandrag: 'Sommarmarknad i Jostedalen 2005 med skathellekasting på programmet.', url: 'https://www.nb.no/items/ae68266b99b10422f08cbabe87215eca?page=19&search=' },
  { ar: 2006, fil: '2006_marknadshelgi_oppsett.png', tittel: 'Marknadshelgi 2006 — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for marknadshelgi i Jostedalen 2006 med skathellekasting.', url: 'https://www.nb.no/items/b5da8b751758108c5e64bc4a9fbe39f4?page=17&search=' },
  { ar: 2007, fil: '2007_skathellekurs.png', tittel: 'Skathellekurs mot forgubbing', avis: 'Sogn Avis', samandrag: 'Fem unge jostedøler og ein immigrant deltok på nybyrjarkurs i skathellekasting. "Me lyt prøva å motverka forgubbinga i skathellekastingmiljøet," seier Britt Elin Fossøy. Norvald Bakken er instruktør. Sporten har vorte ein "elitesport" der erfarne tek heim premiane — kurset skal endre det og få unge med.', url: 'https://www.nb.no/items/833745e7e63afea61d259e17fc66ea7c?page=15&search=' },
  { ar: 2007, fil: '2007_marknadshelgi.png', tittel: 'Marknadshelgi 2007', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2007.', url: 'https://www.nb.no/items/8eb59f00d43b21ec0ad7bfd7147e49d1?page=17&search=' },
  { ar: 2008, fil: '2008_marknadshelgi.png', tittel: 'Marknadshelgi 2008', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2008 med skathellekasting.', url: 'https://www.nb.no/items/9ccb3e27e2ef788786a497e49c98cb03?page=23&search=' },
  { ar: 2008, fil: '2008_marknadhelga_oppsett.png', tittel: 'Marknadshelga — oppsett', avis: 'Lokalavis', samandrag: 'Oppsett for marknadshelgi i Jostedalen 2008.', url: 'https://www.nb.no/items/9ccb3e27e2ef788786a497e49c98cb03?page=23&search=' },
  { ar: 2009, fil: '2009_marknad.png', tittel: 'Marknad 2009', avis: 'Lokalavis', samandrag: 'Marknad i Jostedalen 2009 med skathellekasting.', url: 'https://www.nb.no/items/d227ff55d6f81338d1c75daaec71df7c?page=15&search=' },
  { ar: 2009, fil: '2009_marnadshelgi.png', tittel: 'Marknadshelgi 2009', avis: 'Lokalavis', samandrag: 'Marknadshelg i Jostedalen 2009.', url: 'https://www.nb.no/items/d227ff55d6f81338d1c75daaec71df7c?page=15&search=' },
  { ar: 2010, fil: '2010_Tevlar_i_skathellekasting.png', tittel: 'Tevlar i skathellekasting', avis: 'Sogn Avis', samandrag: '"Steinane flyg høgt og hardt på skathellebana ved Dølaheimen. Konkurranselystne jostedøler har tevla i ein særs lokal-tradisjonell sportsgrein." Ny generasjon kjem til — turneringa vert arrangert kvar veke gjennom sommaren. Totalt 16 deltakarar dette året, og det vert oppretta ein eigen junior-serie.', url: 'https://www.nb.no/items/1fb3f56af8b4b8cc506aae9b0364d1f4?page=9&search=' },
  { ar: 2010, fil: '2010_summarmarknad.png', tittel: 'Sommarmarknad 2010', avis: 'Lokalavis', samandrag: 'Sommarmarknad i Jostedalen 2010 med skathellekasting.', url: 'https://www.nb.no/items/55dffc6ef4548ff70c7f212f7579d598?page=17&search=' },
  { ar: 2018, fil: '2018_vinnarar.png', tittel: 'Skathellekonkurranse på marknaden 2018', avis: 'Sogn Avis', samandrag: 'Skathellekonkurranse under marknadshelgi i Dølaheimen. Tre lag deltok. Vinnarlag: Per Bakkane, Svein Vigdal og Ivar Karlsen. Øyvind Hoel vann terrenggløpet, og det var vekt-tipping på fenalår frå Brelam. Foto: Olav Grov.', url: '' },
  { ar: 2019, fil: '2019_vinnarar.png', tittel: 'Marknad i Dølaheimen — skathellekasting og boklansering', avis: 'Sogn Avis', samandrag: 'Skathellekonkurransen vart halden under marknadshelgi 2019. Vinnarlag: Ingar Norberg, André Olsen Aadland og Steinar Halvveg. Boklansering med Magne Medhus, og Hallgeir Elvehøy frå NVE heldt føredrag om Jostedalsbreen på Breheimsenteret.', url: '' },
  { ar: 2022, fil: '2022_vinnarar.png', tittel: 'Skathellekasting på marknadshelgi 2022', avis: 'Sogn Avis', samandrag: 'Skathellekonkurransen vart halden under marknadshelgi 6. august 2022. Vinnarlag: Erling Sperle, Ingar Norberg og Nils Neset. Henning Skjervik, marknadssjef, deltok aktivt i konkurransen. Foto: Olav Grov.', url: '' },
  { ar: 2023, fil: '2023_vinnarar.png', tittel: 'Ein heil dag på skathellebana gav resultat', avis: 'Sogn Avis', samandrag: 'Reportasje frå skathellekonkurransen 1. august 2023, skriven av Magnus Grotle Førde. Vinnarlag: Arne Fossøy, Even Loe og Ingar Norberg.', url: 'https://www.sognavis.no/5-115-1021394' },
  { ar: 2024, fil: '2024_vinnarar.jpg', tittel: 'Skathellekonkurransen — tradisjon i Jostedalen', avis: 'Sogn Avis', samandrag: 'Reportasje frå marknaden i Dølaheimen 2024. Marknadssjef Ruud fortel at skathellekastinga er det som trekkjer mest folk. Vinnarlag: Arne Fossøy, Nils Neset og Ingar Norberg.', url: '' },
  { ar: 2025, fil: '2025_unge_utovarar.png', tittel: 'Marknad og ein særs sjeldan sport — "Eg hugsar aldri reglane"', avis: 'Sogn Avis', samandrag: 'Reportasje om unge utøvarar — Jan Skamsar Aasen, Brage Norberg og Brage Aasen. Vinnarlag 2025: Per Bakkane, Svein Vigdal og Ivar Karlsen. Foto: Pål S. Bringe. Tilleggskjelde: JSA nr. 44, 2025.', url: '' }
];

(function() {
  const grid   = document.getElementById('arkGrid');
  const count  = document.getElementById('arkCount');
  const filter = document.getElementById('arkFilter');
  if (!grid) return;

  let activeFilter = 'all';

  function render() {
    const filtered = activeFilter === 'all'
      ? arkivKjelder
      : arkivKjelder.filter(k => String(Math.floor(k.ar / 10) * 10) === activeFilter);

    count.textContent = `Viser ${filtered.length} av ${arkivKjelder.length} kjelder`;

    grid.innerHTML = filtered.map(k => `
      <article class="ark-card">
        <button class="ark-img-btn" onclick="openArkLightbox('Bilder/${k.fil}','${k.tittel.replace(/'/g,"\\'")}')">
          <img src="Bilder/${k.fil}" alt="${k.tittel}" loading="lazy" onerror="this.onerror=null;this.src='Bilder/UtenBilde.png';">
        </button>
        <div class="ark-card-body">
          <div class="ark-year">${k.ar}</div>
          <p class="ark-avis">${k.avis}</p>
          <h3 class="ark-tittel">${k.tittel}</h3>
          <p class="ark-samandrag">${k.samandrag}</p>
          ${k.url ? `<a href="${k.url}" class="ark-link" target="_blank" rel="noopener noreferrer">Les på nb.no &#8594;</a>` : ''}
        </div>
      </article>
    `).join('');
  }

  filter.addEventListener('click', e => {
    if (!e.target.matches('.ark-pill')) return;
    filter.querySelectorAll('.ark-pill').forEach(b => b.classList.remove('is-active'));
    e.target.classList.add('is-active');
    activeFilter = e.target.dataset.decade;
    render();
  });

  window.openArkLightbox = function(src, alt) {
    const lb  = document.getElementById('arkLightbox');
    const img = document.getElementById('arkLightboxImg');
    if (lb && img) { img.src = src; img.alt = alt; lb.classList.add('is-open'); lb.setAttribute('aria-hidden','false'); }
  };

  const lbClose = document.getElementById('arkLightboxClose');
  const lb = document.getElementById('arkLightbox');
  if (lbClose && lb) {
    lbClose.addEventListener('click', () => { lb.classList.remove('is-open'); lb.setAttribute('aria-hidden','true'); });
    lb.addEventListener('click', e => { if (e.target === lb) { lb.classList.remove('is-open'); lb.setAttribute('aria-hidden','true'); }});
    document.addEventListener('keydown', e => { if (e.key === 'Escape') { lb.classList.remove('is-open'); lb.setAttribute('aria-hidden','true'); }});
  }

  render();
})();
